services:
  postgres:
    image: postgres:17
    container_name: geoquest-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: geoquest
      POSTGRES_PASSWORD: geoquest
      POSTGRES_DB: geoquest

    ports:
      - '5432:5432'

    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: geoquest-redis

    restart: unless-stopped

    ports:
      - '6379:6379'

    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
